#!/usr/bin/env bash
# Ops Master Agent - one-command dev startup (Linux/WSL).
# Checks required tooling (Node.js 18+, optionally Docker), installs
# project dependencies, ensures a working local .env exists, then starts
# the server (:4100) and web UI (:5173) in the background.
# Run ./stop-app.sh to stop them. Safe to re-run.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

# --- helpers ----------------------------------------------------------------
step()  { printf '\033[36m==> %s\033[0m\n' "$*"; }
ok()    { printf '\033[32mOK  %s\033[0m\n' "$*"; }
warn()  { printf '\033[33m!!  %s\033[0m\n' "$*"; }
fail()  { printf '\033[31mXX  %s\033[0m\n' "$*"; }

# --- 1. Required tooling ---------------------------------------------------
if ! command -v node &>/dev/null || ! command -v npm &>/dev/null; then
  fail "Node.js is not available on PATH."
  echo "Install Node.js 18+ LTS from https://nodejs.org/ (or use nvm/fnm), then re-run this script."
  exit 1
fi

NODE_VERSION="$(node --version | sed 's/^v//')"
MAJOR_VERSION="${NODE_VERSION%%.*}"
if [ "$MAJOR_VERSION" -lt 18 ]; then
  fail "Node.js $NODE_VERSION found, but 18+ is required."
  echo "Upgrade from https://nodejs.org/ or via your package manager."
  exit 1
fi
ok "node v$NODE_VERSION, npm $(npm --version)"

if command -v docker &>/dev/null; then
  ok "docker found: $(docker --version)"
else
  warn "docker CLI not found - the pipeline still runs and demos fully (mock deploy/rollback path)."
  echo "Install Docker for live container deploys: https://docs.docker.com/engine/install/"
fi

# --- 2. Project dependencies ------------------------------------------------
if [ ! -d "$ROOT/node_modules" ]; then
  step "node_modules missing - running npm install (first run, may take a minute)..."
  npm install
else
  ok "dependencies already installed"
fi

# --- 3. Build shared contracts package --------------------------------------
step "Building @ops-master/shared..."
npm run build -w @ops-master/shared
ok "shared contracts built"

# --- 4. Ensure a working local server .env exists ---------------------------
ENV_PATH="$ROOT/apps/server/.env"
if [ ! -f "$ENV_PATH" ]; then
  step "apps/server/.env missing - creating a local, mock-mode default (no API keys required to start)"
  cat > "$ENV_PATH" << 'EOF'
# Auto-generated by start-app.sh - safe local defaults, runs fully offline.
# Fill in real values any time; see apps/server/.env.example for details.
ANTHROPIC_API_KEY=
ANTHROPIC_MODEL=claude-sonnet-4-5
MOCK_LLM=true

SUPABASE_URL=
SUPABASE_SERVICE_ROLE_KEY=

DEPLOY_TARGET=compose
DEPLOYMENTS_DIR=./deployments
MOCK_DEPLOY=auto
SKIP_LOAD_TEST=true

PORT=4100
APPROVAL_TIMEOUT_MINUTES=30
EOF
  ok "created apps/server/.env (mock mode)"
else
  ok "apps/server/.env already present"
fi

# --- 5. Stop any previous instance, then launch fresh ----------------------
RUN_DIR="$ROOT/.run"
mkdir -p "$RUN_DIR"
if [ -x "$ROOT/stop-app.sh" ]; then
  "$ROOT/stop-app.sh" --quiet
fi

step "Starting server (http://localhost:4100)..."
nohup npm run dev -w @ops-master/server > "$RUN_DIR/server.log" 2> "$RUN_DIR/server.err.log" &
echo $! > "$RUN_DIR/server.pid"

step "Starting web UI (http://localhost:5173)..."
nohup npm run dev -w @ops-master/web > "$RUN_DIR/web.log" 2> "$RUN_DIR/web.err.log" &
echo $! > "$RUN_DIR/web.pid"

# --- 6. Wait for the server to report healthy -------------------------------
step "Waiting for server to become healthy..."
HEALTHY=false
for i in $(seq 1 40); do
  sleep 0.5
  if curl -sf --max-time 2 http://localhost:4100/api/health 2>/dev/null | grep -q '"ok"'; then
    HEALTHY=true
    break
  fi
done

echo ""
if [ "$HEALTHY" = true ]; then
  ok "Ops Master Agent is running"
else
  warn "server did not report healthy within 20s - check .run/server.log and .run/server.err.log"
fi
echo "  Web UI:  http://localhost:5173"
echo "  Server:  http://localhost:4100/api/health"
echo "  Logs:    .run/server.log / .run/web.log"
echo "  Stop:    ./stop-app.sh"
echo ""
